Django/RssfeedS/RssfeedS/urls.py
from django.contrib import admin
from django.urls import path, include
from articlefeeds import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('rss-feeds/', include('articlefeeds.urls')),

    path('article-post/', views.article_post),
    path('article-list/', views.article_list),
    path('article-edit/<int:id>', views.article_edit),
    path('article-update/<int:id>', views.article_update),
    path('article-delete/<int:id>', views.article_destroy),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django/RssfeedS/articlefeeds/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [

    path('', views.home, name='home'),
    path('accounts/', include('django.contrib.auth.urls')),

    path('signup/', views.signup, name='signup'),
    path('category/', views.category, name='category'),
    path('article-post/', views.article_post, name='article-post'),
    path('article-list/', views.article_list, name='article-list'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django/RssfeedS/articlefeeds/models.py
from django.db import models
from datetime import datetime

CATEGORY = (
    ('1', 'Sports'),
    ('2', 'Politics'),
    ('3', 'Space'),
    ('4', 'Other'),
)


class PostArticle(models.Model):
    name = models.CharField(max_length=82)
    description = models.TextField()
    images = models.ImageField(upload_to='UploadedFiles/%Y/%b/', blank=True, null=True)
    # images = models.FileField()
    img_captions = models.CharField(max_length=15)
    tags = models.CharField(max_length=82)
    category = models.CharField(max_length=1, choices=CATEGORY)

    date_of_posted = models.DateTimeField(default=datetime.now)
    # user_name = models.CharField(default=User.username, max_length=25)
    email_id = models.EmailField(default='a@gmail.coom', max_length=25)

    def __str__(self):
        return '%s' % self.name

Django/RssfeedS/articlefeeds/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import PostArticle, CATEGORY


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True, help_text='Required.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    dob = forms.DateField()
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')
    article_category = forms.TypedChoiceField(choices=CATEGORY)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )


class PostArticleForm(forms.ModelForm):
    """ POST Article Form. """
    name = forms.CharField(
        label='',
        required=True,
        widget=forms.TextInput(
            attrs={'class': 'comment_input', 'name': 'Name',
                   'placeholder': 'Article Name'}
        )
    )

    # images = forms.FileField(
    #     label='',
    #     required=True,
    #     widget=forms.FileField(
    #         attrs={'class': 'comment_input', 'name': 'images'}
    #     )
    # )

    img_captions = forms.CharField(
        label='',
        required=True,
        widget=forms.TextInput(
            attrs={'class': 'comment_input', 'name': 'img_captions',
                   'placeholder': 'Image Caption'}
        )
    )

    description = forms.CharField(
        label='',
        required=True,
        widget=forms.Textarea(
            attrs={'class': 'comment_input', 'name': 'description',
                   'placeholder': 'Article Description'}
        )
    )

    # category = forms.CharField(
    #     label='',
    #     required=True,
    #     widget=forms.TextInput(
    #         attrs={'class': 'comment_input', 'name': 'category'}
    #     )
    # )

    tags = forms.CharField(
        label='',
        required=False,
        widget=forms.TextInput(
            attrs={'class': 'comment_input', 'name': 'tags',
                   'placeholder': 'Add Tag optional'}
        )
    )

    class Meta:
        model = PostArticle
        fields = ['name', 'images', 'img_captions', 'description', 'category', 'tags']

Django/RssfeedS/articlefeeds/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import login, authenticate
from .forms import SignUpForm, PostArticleForm
from .models import PostArticle


def home(request):
    count = User.objects.count()
    return render(request, 'home.html', {
        'count': count
    })


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            # USERNAME_FIELD = user.username
            login(request, user)
            return redirect('home')
    else:
        form = SignUpForm()
    return render(request, 'registration/signup.html', {'form': form})


@login_required
def post(request):
    return render(request, 'post.html')


@login_required
def category(request):
    return render(request, 'category.html')


@login_required
def article_post(request):
    """ S23 Conference Registration Form. """

    def handle_uploaded_file(f):
        with open('articlefeeds/static/img/upload/' + f.name, 'wb+') as destination:
            for chunk in f.chunks():
                destination.write(chunk)

    if request.method == "POST":
        form = PostArticleForm(request.POST, request.FILES)
        if form.is_valid():
            handle_uploaded_file(request.FILES['images'])
            form.save()
            return redirect("article-list")
    else:
        form = PostArticleForm()
    return render(request, 'article_post.html', {'form': form})


@login_required
def article_list(request):
    """ S23.1 post_article Registered List. """
    # print((USERNAME_FIELD), "$"*33)
    # for i, j in User.username:
    #     print(i, j)
    articles = PostArticle.objects.all().order_by('-id')
    return render(request, 'article_list.html', {'articles': articles})


@login_required
def article_edit(request, id):
    """ S23.2 post_article Form Edit. """

    article = PostArticle.objects.get(id=id)
    return render(request, 'article_edit.html', {'article': article})


@login_required
def article_update(request, id):
    """ S23.3 post_article Form Update. """

    article = PostArticle.objects.get(id=id)
    form = PostArticleForm(request.POST, instance=article)
    if form.is_valid():
        form.save()
        return redirect("/article-list")
    return render(request, 'article_edit.html', {'article': article})


@login_required
def article_destroy(request, id):
    """ S23.4 post_article Form Delete. """

    user_article = PostArticle.objects.get(id=id)
    user_article.delete()
    return redirect("/article-list")


class SecretPage(LoginRequiredMixin, TemplateView):
    template_name = 'home.html'

Django/RssfeedS/articlefeeds/templates/article_edit.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

<!-- Page Content -->
<link rel="stylesheet" type="text/css" href="{% static '/styles/post.css' %}">

   
 <!--Update Article-->

<div class="post_comment">
    <div class="post_comment_title">Post Article</div>
    <div class="row">
        <div class="col-xl-12">
            <div class="post_comment_form_container">
                <form method="POST" class="post-form" enctype="multipart/form-data">
                    {% csrf_token %}

                    <input type="text" class="comment_text" style="height:55px" placeholder="Article Name" required="required" name="name" id="id_name" >
                    <label class="col-sm-2 col-form-label"> Article Name:</label>
                    <input type="text" class="comment_text" style="height:35px"  name="name" id="id_name" required="required"  value="{{ article.name }}" />

                    <input type="file"  class="comment_input comment_input_name"  style="height:55px"    name="images" id="id_images" accept="image/*" >
                    <input type="text" class="comment_input comment_input_name"  style="height:88px"  placeholder="Image Caption" required="required" name="img_captions" id="id_img_captions" >

                    <img src="{{ article.images.url }}" height="50px" width="50px">
                    <input type="file"   class="comment_text" style="height:55px"    name="images" id="id_images" accept="image/*" >

                    <label class="col-sm-2 col-form-label"> Image Caption:</label>
                    <input type="text" class="comment_text"  style="height:35px"  required="required" name="img_captions" id="id_img_captions" value="{{ article.img_captions }}" >

                    <select  class="comment_input comment_input_name" required="required"   style="height:80px"  name="category" id="id_category">
                        <option value selected> Select Category</option>
                        <option value="1">Sports</option>
                        <option value="2">Politics</option>
                        <option value="3">Space</option>
                        <option value="4">Other</option>
                    </select>
                    <input type="text" class="comment_input comment_input_name"   style="height:80px"   placeholder="Add Tags Optional"  name="img_tags" id="id_tags" >

                    <textarea class="comment_text" placeholder="Article Description" required="required" name="description" id="id_description"></textarea>
                    <button type="submit" class="comment_button">POST</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Django/RssfeedS/articlefeeds/templates/article_list.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

<!-- page content -->
<link rel="stylesheet" type="text/css" href="{% static '/styles/post.css' %}">

{% for article in articles %}

<div class="row row-lg-eq-height">

    <!-- Post Content -->
    <div class="col-lg-12">
        <div class="post_content">
            <!-- Top Panel -->
            <div class="post_panel post_panel_top d-flex flex-row align-items-center justify-content-start">
                <div class="author_image"><div><img src="{% static '/images/user1.jpg' %}" alt="User DP"></div></div>
                <div class="post_meta">
                    {% if user.is_authenticated %} {{ user.username.capitalize }}{% else %}visitor{% endif %}
                    <span> {{ article.date_of_posted }}</span>
                </div>
            </div>

            <!-- Post Body -->

            <div class="post_body">
                <p class="post_p">
                    {{ article.name }}
                </p>
                <figure>
                      {% if article.images.url %}
                          <img src="{{ article.images.url }}" >
                      {% else %}1
                          <img src="{% static '/images/post_11.jpg' %}" width="340px">
                      {% endif %}
                    <figcaption>{{ article.img_captions }}</figcaption>
                </figure>
                <p class="post_p">
                    {{ article.description }}
                </p>
                <hr>
                <p class="post_p" style="float: right;">
                    <a href="/article-edit/{{ article.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>
                    <a href="/article-delete/{{ article.id }}">Delete</a>
                </p>
            </div>

        </div>

    </div>


</div>




    {% endfor %}
{% endblock %}

Django/RssfeedS/articlefeeds/templates/article_post.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

<!-- Page Content -->
<link rel="stylesheet" type="text/css" href="{% static '/styles/post.css' %}">

 <!--Post Content-->
<div class="post_comment">
    <div class="post_comment_title">Post Article</div>
    <div class="row">
        <div class="col-xl-12">
            <div class="post_comment_form_container">
                <form method="POST" class="post-form" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <!--<input type="text" class="comment_text" style="height:55px" placeholder="Article Name" required="required" name="name" id="id_name" >-->
                    <!--<input type="file"  class="comment_input"  style="height:55px"    name="images" id="id_images" accept="image/*" >-->
                    <!--<input type="text" class="comment_input"  style="height:88px"  placeholder="Image Caption" required="required" name="img_captions" id="id_img_captions" >-->
                    <!--<select  class="comment_input comment_input_name" required="required"   style="height:80px"  name="category" id="id_category">-->
                        <!--<option value selected> Select Category</option>-->
                        <!--<option value="1">Sports</option>-->
                        <!--<option value="2">Politics</option>-->
                        <!--<option value="3">Space</option>-->
                        <!--<option value="4">Other</option>-->
                    <!--</select>-->
                    <!--<input type="text" class="comment_input comment_input_name"   style="height:80px"   placeholder="Add Tags Optional"  name="img_tags" id="id_tags" >-->

                    <!--<textarea class="comment_text" placeholder="Article Description" required="required" name="description" id="id_description"></textarea>-->
                    <button type="submit" class="comment_button">POST</button>
                </form>
            </div>
        </div>
    </div>
</div>


{% endblock %}

Django/RssfeedS/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>RssFeeds</title>

        <meta charset="UTF-8">
        <meta name="description" content="Rss Feeds">
        <meta name="keywords" content="Rss Feeds, News, Article, ARS, RASyS">
        <meta name="author" content="Ravi ARS">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">

        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static '/styles/bootstrap4/bootstrap.min.css' %}">
        <link href="{% static '/plugins/font-awesome-4.7.0/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
        <link rel="stylesheet" type="text/css" href="{% static '/plugins/OwlCarousel2-2.2.1/owl.carousel.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static '/plugins/OwlCarousel2-2.2.1/owl.theme.default.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static '/plugins/OwlCarousel2-2.2.1/animate.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static '/plugins/jquery.mb.YTPlayer-3.1.12/jquery.mb.YTPlayer.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static '/styles/main_styles.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static '/styles/responsive.css' %}">
    </head>
    <body>
        <!-- Body -->
        <div class="super_container">

            <!-- Header -->
            <header class="header">
                <div class="container">
                    <div class="row">
                        <div class="col">
                            <div class="header_content d-flex flex-row align-items-center justify-content-start">
                                <div class="logo"><a href="{% url 'home' %}">RssfeedS</a></div>
                                <nav class="main_nav">
                                    <ul>
                                        <li class="active"><a href="{% url 'home' %}">Home</a></li>
                                        {% if user.is_authenticated %}
                                        <li class="nav-item">
                                          <a class="nav-link" href="{% url 'category' %}">Category</a>
                                        </li>
                                        <li class="nav-item">
                                          <a class="nav-link" href="{% url 'article-post' %}">Article Post</a>
                                        </li>
                                        <li class="nav-item">
                                          <a class="nav-link" href="{% url 'article-list' %}">Article List</a>
                                        </li>
                                        {% endif %}
                                    </ul>
                                </nav>
                                <div class="search_container ml-auto">
                                    {% if user.is_authenticated %}
                                      <ul class="navbar-nav">
                                        <li class="nav-item dropdown">
                                          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            {{ user.username }}
                                          </a>
                                          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                            <!--<a class="dropdown-item" href="{% url 'password_change' %}">Profile</a>-->
                                            <!--<div class="dropdown-divider"></div>-->
                                            <a class="dropdown-item" href="{% url 'password_change' %}">Change password</a>
                                            <div class="dropdown-divider"></div>
                                            <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
                                          </div>
                                        </li>
                                      </ul>
                                    {% else %}
                                      <form class="form-inline my-2 my-lg-0">
                                        <a href="{% url 'login' %}" class="btn btn-outline-secondary">Log in</a>
                                        <a href="{% url 'signup' %}" class="btn btn-primary ml-2">Sign up</a>
                                      </form>
                                    {% endif %}

                                </div>
                                <div class="hamburger ml-auto menu_mm">
                                    <i class="fa fa-bars trans_200 menu_mm" aria-hidden="true"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </header>

            	<!-- Menu -->

            <div class="menu d-flex flex-column align-items-end justify-content-start text-right menu_mm trans_400">
                <div class="menu_close_container"><div class="menu_close"><div></div><div></div></div></div>
                <div class="logo menu_mm"><a href="{% url 'home' %}">RssFeeds</a></div>
                <div class="search">
                    {% if user.is_authenticated %}
                      <ul class="navbar-nav">
                        <li class="nav-item dropdown">
                          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{ user.username }}
                          </a>
                          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <!--<a class="dropdown-item" href="{% url 'password_change' %}">Profile</a>-->
                            <!--<div class="dropdown-divider"></div>-->
                            <a class="dropdown-item" href="{% url 'password_change' %}">Change password</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
                          </div>
                        </li>
                      </ul>
                    {% endif %}
                </div>
                <nav class="menu_nav">
                    <ul class="menu_mm">
                        <li class="menu_mm"><a href="{% url 'home' %}">Home</a></li>
                        {% if user.is_authenticated %}
                        <li class="menu_mm"><a href="{% url 'category' %}">Category</a></li>
                        <li class="menu_mm"><a href="{% url 'article-post' %}">Article Post</a></li>
                        <li class="menu_mm"><a href="{% url 'article-list' %}">Article list</a></li>

                        {% else %}

                            <li class="menu_mm"><a href="{% url 'login' %}" class="btn btn-outline-secondary">Log in</a></li>
                            <li class="menu_mm"><a href="{% url 'signup' %}" class="btn btn-primary ml-2">Sign up</a></li>
                        {% endif %}

                    </ul>
                </nav>
            </div>
            <!-- Load Latest news future enhancement-->
            <div class="load_more">
            </div>

             <!--Page Content -->
            <div class="page_content">
                <div class="container">
                        {% block content %}
                        {% endblock %}
                </div>
            </div>

            <!-- Load old news future enhancement-->
            <div class="load_more">
            </div>

            <!-- Footer -->
            <footer class="footer">
                <div class="container">
                    <div class="row row-lg-eq-height">
                        <div class="col-lg-12 order-lg-1 order-2">
                            <div class="footer_content">
                                <div class="footer_logo"><a href="#">RssFeedS</a></div>
                                <div class="footer_social">
                                    <ul>
                                        <li class="footer_social_github"><a href="https://github.com/RaviARS"><i class="fa fa-github" aria-hidden="true"></i></a></li>
                                        <li class="footer_social_facebook"><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                                        <li class="footer_social_twitter"><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                                        <li class="footer_social_pinterest"><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
                                        <li class="footer_social_vimeo"><a href="#"><i class="fa fa-vimeo" aria-hidden="true"></i></a></li>
                                        <li class="footer_social_instagram"><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                                        <li class="footer_social_google"><a href="#"><i class="fa fa-google" aria-hidden="true"></i></a></li>
                                    </ul>
                                </div>
                                <div class="copyright">
                                    Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | Developed by  <a href="https://ars.pythonanywhere.com" target="_blank"> RASyS</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </footer>

        </div>

        <script src="{% static '/js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static '/styles/bootstrap4/popper.js' %}"></script>
        <script src="{% static '/styles/bootstrap4/bootstrap.min.js' %}"></script>
        <script src="{% static '/plugins/OwlCarousel2-2.2.1/owl.carousel.js' %}"></script>
        <script src="{% static '/plugins/jquery.mb.YTPlayer-3.1.12/jquery.mb.YTPlayer.js' %}"></script>
        <script src="{% static '/plugins/easing/easing.js' %}"></script>
        <script src="{% static '/plugins/masonry/masonry.js' %}"></script>
        <script src="{% static '/plugins/masonry/images_loaded.js' %}"></script>
        <script src="{% static '/js/custom.js' %}"></script>

    </body>
</html>